"""Write a stored potential grid back out as OpenDX, for PyMOL/ChimeraX/VMD.

The volumetric map lives in the HDF5 as compressed float32, which is roughly
40x smaller than the OpenDX text it came from -- so rather than keeping DX
files around, regenerate one on demand for whichever model is being looked at.

    python -m apbs_analysis.export_dx ~/Documents/apbs_electrostatics_84_targets/targets_84_apbs_surface.hdf5 1acb
"""

from __future__ import annotations

import argparse
import gzip
from pathlib import Path
import sys

import numpy as np

from apbs_analysis.analysis import load_potential_grid
from apbs_analysis.dx_grid import DxGrid


def write_dx(grid: DxGrid, output_path: str | Path, values_per_line: int = 3) -> Path:
    """Emit a uniform OpenDX file; .gz suffix writes it compressed."""
    output_path = Path(output_path)
    nx, ny, nz = grid.shape
    header = (
        f"# Regenerated by apbs_analysis.export_dx\n"
        f"object 1 class gridpositions counts {nx} {ny} {nz}\n"
        f"origin {grid.origin[0]:.6e} {grid.origin[1]:.6e} {grid.origin[2]:.6e}\n"
        f"delta {grid.spacing[0]:.6e} 0.000000e+00 0.000000e+00\n"
        f"delta 0.000000e+00 {grid.spacing[1]:.6e} 0.000000e+00\n"
        f"delta 0.000000e+00 0.000000e+00 {grid.spacing[2]:.6e}\n"
        f"object 2 class gridconnections counts {nx} {ny} {nz}\n"
        f"object 3 class array type double rank 0 items {nx * ny * nz} data follows\n"
    )
    footer = (
        'attribute "dep" string "positions"\n'
        'object "regular positions regular connections" class field\n'
        'component "positions" value 1\n'
        'component "connections" value 2\n'
        'component "data" value 3\n'
    )

    flat = grid.values.reshape(-1)  # OpenDX is z-fastest, matching the stored order
    padded = np.pad(flat, (0, (-flat.size) % values_per_line), constant_values=np.nan)
    rows = padded.reshape(-1, values_per_line)

    opener = gzip.open if output_path.suffix == ".gz" else open
    with opener(output_path, "wt", encoding="utf-8") as handle:
        handle.write(header)
        for row in rows:
            handle.write(" ".join(f"{value:.6e}" for value in row if not np.isnan(value)) + "\n")
        handle.write(footer)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("hdf5_path")
    parser.add_argument("model_id")
    parser.add_argument("-o", "--output", help="Output path (default: <model_id>_potential.dx in the CWD)")
    parser.add_argument("--gzip", action="store_true", help="Write a .dx.gz instead")
    args = parser.parse_args()

    try:
        grid = load_potential_grid(args.hdf5_path, args.model_id)
    except KeyError as exc:
        sys.exit(str(exc))

    output = Path(args.output) if args.output else Path(f"{args.model_id}_potential.dx{'.gz' if args.gzip else ''}")
    write_dx(grid, output)
    print(f"Wrote {output} ({output.stat().st_size / 1024**2:.1f} MiB), grid {grid.shape}")


if __name__ == "__main__":
    main()
