"""Unpack a stored model into files PyMOL can open, plus a session script.

PyMOL cannot read the HDF5 store, so this writes, per model:

  <id>.pqr                    structure with the PARSE charges and radii APBS used
  <id>_potential.dx.gz        the volumetric potential (kT/e), for ramp colouring
                              (PyMOL reads gzipped maps directly; 63 MB -> 24 MB)
  <id>_residue_potential.pdb  same structure, B-factor = that residue's mean
                              surface potential (buried residues get the sentinel)
  <id>_surface_points.pdb     optional: the SAS point cloud as pseudo-atoms,
                              B-factor = potential at that point
  <id>.pml                    loads the above and sets up the usual views

Everything is written in the source PDB's coordinate frame, so these overlay
directly on the original structure.

    python -m apbs_analysis.pymol_export <store.hdf5> 1acb -o ~/Documents/pymol
    python -m apbs_analysis.pymol_export <store.hdf5> --all -o ~/Documents/pymol
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import h5py
import numpy as np

from apbs_analysis.analysis import load_potential_grid
from apbs_analysis.common import IN_PROGRESS_PREFIX
from apbs_analysis.export_dx import write_dx


# PyMOL shows B-factor as-is, so buried residues need a value that cannot be
# mistaken for a real potential. -999 sits far outside any physical range and
# is easy to exclude with a selection.
BURIED_SENTINEL = -999.0


def _pdb_line(
    record: str, serial: int, atom_name: str, resname: str, chain: str,
    resnum: int, xyz, occupancy: float, bfactor: float, element: str,
) -> str:
    # B-factor is a %6.2f field: anything outside +/-999.99 would overflow it.
    bfactor = float(np.clip(bfactor, -999.99, 999.99))
    name = f" {atom_name:<3s}" if len(atom_name) < 4 else atom_name[:4]
    return (
        f"{record:<6s}{serial:5d} {name}{'':1s}{resname:>3s} {chain:1s}{resnum:4d}    "
        f"{xyz[0]:8.3f}{xyz[1]:8.3f}{xyz[2]:8.3f}{occupancy:6.2f}{bfactor:6.2f}"
        f"{'':10s}{element:>2s}"
    )


def write_pqr_from_store(group: h5py.Group, path: Path) -> Path:
    """Re-emit the structure as PQR: coordinates, PARSE charge, PARSE radius."""
    chain = group["atom_chain"].asstr()[:]
    resnum = group["atom_resnum"][:]
    resname = group["atom_resname"].asstr()[:]
    atom_name = group["atom_name"].asstr()[:]
    xyz = group["atom_xyz"][:]
    charge = group["atom_charge"][:]
    radius = group["atom_radius"][:]

    lines = [
        f"REMARK   1 PQR regenerated by apbs_analysis.pymol_export from {group.name}",
        f"REMARK   1 charges and radii are the PARSE values APBS was given",
    ]
    for index in range(len(xyz)):
        lines.append(
            f"ATOM  {index + 1:5d} {atom_name[index]:<4s} {resname[index]:<3s} "
            f"{chain[index] or ' ':1s} {resnum[index]:5d} "
            f"{xyz[index, 0]:12.4f} {xyz[index, 1]:12.4f} {xyz[index, 2]:12.4f} "
            f"{charge[index]:9.4f} {radius[index]:8.4f}"
        )
    lines += ["TER", "END"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_residue_potential_pdb(group: h5py.Group, path: Path) -> tuple[Path, float, float]:
    """Structure with B-factor set to each residue's mean surface potential."""
    atom_aa_id = group["atom_aa_id"][:]
    residue_potential = group["residue_potential_mean"][:].astype(np.float64)
    values = np.where(np.isfinite(residue_potential), residue_potential, BURIED_SENTINEL)

    chain = group["atom_chain"].asstr()[:]
    resnum = group["atom_resnum"][:]
    resname = group["atom_resname"].asstr()[:]
    atom_name = group["atom_name"].asstr()[:]
    xyz = group["atom_xyz"][:]
    radius = group["atom_radius"][:]

    lines = [
        "REMARK   1 B-factor = area-weighted mean surface potential of the residue, kT/e",
        f"REMARK   1 buried residues (no solvent-accessible surface) carry {BURIED_SENTINEL:.0f}",
    ]
    for index in range(len(xyz)):
        element = atom_name[index][:1]
        # PARSE gives aliphatic hydrogens radius 0.0 (they are united into their
        # carbon); recover the element from the name so PyMOL still draws
        # sensible bonds.
        if radius[index] == 0.0:
            element = "H"
        lines.append(
            _pdb_line(
                "ATOM", index + 1, atom_name[index], resname[index], chain[index] or " ",
                int(resnum[index]), xyz[index], 1.0, values[atom_aa_id[index]], element,
            )
        )
    lines += ["TER", "END"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    real = residue_potential[np.isfinite(residue_potential)]
    return path, (float(real.min()) if real.size else 0.0), (float(real.max()) if real.size else 0.0)


def write_surface_points_pdb(group: h5py.Group, path: Path, stride: int = 1) -> Path | None:
    """SAS point cloud as pseudo-atoms, B-factor = potential at that point."""
    if "surface_xyz" not in group:
        return None
    xyz = group["surface_xyz"][:][::stride]
    potential = group["surface_potential"][:][::stride]
    residue_index = group["surface_residue_index"][:][::stride]
    residue_chain = group["residue_chain"].asstr()[:]
    residue_number = group["residue_number"][:]

    lines = ["REMARK   1 SAS points; B-factor = electrostatic potential at the point, kT/e"]
    for index in range(len(xyz)):
        parent = residue_index[index]
        lines.append(
            _pdb_line(
                "HETATM", (index % 99999) + 1, "PS", "SRF",
                residue_chain[parent] or " ",
                # PDB residue numbers are a 4-character field; wrap rather than
                # overflow it, since these are display pseudo-atoms only.
                int(residue_number[parent]) % 10000,
                xyz[index], 1.0, float(potential[index]), "H",
            )
        )
    lines += ["END"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


PML_TEMPLATE = '''# {model_id} -- APBS surface electrostatics
# Potentials are in kT/e (multiply by 25.7 for mV at 298 K).
# Generated by apbs_analysis.pymol_export

load {pqr}, {model_id}
{dx_load}
# B-factor on this object is the residue's mean surface potential.
load {res_pdb}, {model_id}_resmap
{points_load}
hide everything
bg_color white

# --- View 1: surface coloured by the potential map itself ---
show surface, {model_id}
set surface_quality, 1
{ramp_block}
# --- View 2: surface coloured by per-residue mean surface potential ---
show surface, {model_id}_resmap
spectrum b, blue_white_red, {model_id}_resmap and b > -900, {res_lo:.2f}, {res_hi:.2f}
color grey60, {model_id}_resmap and b < -900   # buried: no surface to average
disable {model_id}_resmap

set transparency, 0.0
set two_sided_lighting, on
orient {model_id}
/print("Loaded {model_id} | objects: {model_id} (coloured by the map) and {model_id}_resmap (per-residue means).{points_note}")
/print("Per-residue ramp spans {res_lo:.2f} to {res_hi:.2f} kT/e. Grey = buried.")
'''

RAMP_BLOCK = '''ramp_new potential_ramp, {model_id}_potential, [{lo:.2f}, 0, {hi:.2f}], [red, white, blue]
set surface_color, potential_ramp, {model_id}
'''


def write_pml(
    directory: Path, model_id: str, has_grid: bool, has_points: bool,
    res_lo: float, res_hi: float, ramp: float, grid_name: str,
) -> Path:
    dx_load = f"load {grid_name}, {model_id}_potential" if has_grid else \
        "# (no volumetric map exported for this model)"
    ramp_block = RAMP_BLOCK.format(model_id=model_id, lo=-ramp, hi=ramp) if has_grid else \
        f"spectrum b, blue_white_red, {model_id}\n"
    points_load = f"load {model_id}_surface_points.pdb, {model_id}_points\nhide everything, {model_id}_points\n" \
        if has_points else "# (no surface point cloud stored for this model)"
    points_note = " Point cloud in {}_points (hidden - 'show nb_spheres' to see it).".format(model_id) if has_points else ""

    path = directory / f"{model_id}.pml"
    path.write_text(
        PML_TEMPLATE.format(
            model_id=model_id,
            pqr=f"{model_id}.pqr",
            dx_load=dx_load,
            res_pdb=f"{model_id}_residue_potential.pdb",
            points_load=points_load,
            ramp_block=ramp_block,
            res_lo=res_lo,
            res_hi=res_hi,
            points_note=points_note,
        ),
        encoding="utf-8",
    )
    return path


def export_model(
    store_path: Path, model_id: str, output_dir: Path,
    include_points: bool, point_stride: int, ramp: float,
    include_grid: bool = True, gzip_grid: bool = True,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    with h5py.File(store_path, "r") as handle:
        if model_id not in handle:
            raise KeyError(f"{model_id} not in {store_path}")
        group = handle[model_id]
        written.append(write_pqr_from_store(group, output_dir / f"{model_id}.pqr"))
        residue_pdb, res_lo, res_hi = write_residue_potential_pdb(
            group, output_dir / f"{model_id}_residue_potential.pdb"
        )
        written.append(residue_pdb)
        has_points = include_points and "surface_xyz" in group
        if has_points:
            points_path = write_surface_points_pdb(
                group, output_dir / f"{model_id}_surface_points.pdb", stride=point_stride
            )
            if points_path:
                written.append(points_path)
        has_grid = include_grid and "potential_grid" in group

    grid_name = f"{model_id}_potential.dx" + (".gz" if gzip_grid else "")
    if has_grid:
        grid = load_potential_grid(store_path, model_id)
        written.append(write_dx(grid, output_dir / grid_name))

    written.append(
        write_pml(output_dir, model_id, has_grid, has_points, res_lo, res_hi, ramp, grid_name)
    )
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("store_path")
    parser.add_argument("models", nargs="*", help="Model ids to export")
    parser.add_argument("--all", action="store_true", help="Export every model in the store")
    parser.add_argument("-o", "--output-dir", default="apbs_pymol", help="Directory to write into")
    parser.add_argument("--no-points", action="store_true", help="Skip the surface point cloud")
    parser.add_argument("--no-grid", action="store_true",
                        help="Skip the volumetric map (much smaller; per-residue colouring still works)")
    parser.add_argument("--no-gzip", action="store_true",
                        help="Write the map as plain .dx instead of .dx.gz (~2.7x larger)")
    parser.add_argument("--point-stride", type=int, default=1,
                        help="Keep every Nth surface point (thins a large cloud)")
    parser.add_argument("--ramp", type=float, default=5.0,
                        help="Half-range in kT/e for the surface colour ramp (default +/-5)")
    args = parser.parse_args()

    store_path = Path(args.store_path).expanduser()
    if not store_path.is_file():
        sys.exit(f"No store at {store_path}")

    with h5py.File(store_path, "r") as handle:
        available = sorted(name for name in handle if not name.startswith(IN_PROGRESS_PREFIX))
    if args.all:
        models = available
    elif args.models:
        missing = [name for name in args.models if name not in available]
        if missing:
            sys.exit(f"Not in the store: {', '.join(missing)}")
        models = args.models
    else:
        sys.exit("Give one or more model ids, or --all")

    output_dir = Path(args.output_dir).expanduser()
    total = 0
    for index, model_id in enumerate(models, start=1):
        written = export_model(
            store_path, model_id, output_dir,
            include_points=not args.no_points, point_stride=max(1, args.point_stride),
            ramp=args.ramp, include_grid=not args.no_grid, gzip_grid=not args.no_gzip,
        )
        total += len(written)
        if len(models) > 1 and index % 10 == 0:
            print(f"  exported {index}/{len(models)} models", flush=True)

    print(f"Wrote {total} files for {len(models)} model(s) into {output_dir}")
    if len(models) == 1:
        print(f"Open with:  pymol {output_dir / (models[0] + '.pml')}")
    else:
        print(f"Open one with e.g.:  pymol {output_dir / (models[0] + '.pml')}")


if __name__ == "__main__":
    main()
