"""One PyMOL session per complex: the complex, its monomers, and their difference.

pymol_export writes each model independently. This stitches a complex and its
chains into a single session so they can actually be compared -- which is the
point of having monomer maps at all. Because the monomer runs share the
complex's lattice, all the maps load into the same frame and overlay exactly.

Objects created for <id>:
  <id>_complex        complex surface, coloured by the complex potential map
  <id>_<chain>        each isolated chain, coloured by its own map
  <id>_interaction    the complex surface coloured by dphi = complex - sum(chains),
                      i.e. what the partner chain does to the field

Paths are written relative to the directory the .pml lands in, so the whole
folder stays portable as long as its layout is kept.

    python -m apbs_analysis.pymol_compare <complexes.hdf5> <monomers.hdf5> \
        --complex-dir pymol_complexes --monomer-dir pymol_monomers -o .
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

import h5py
import numpy as np

from apbs_analysis.common import IN_PROGRESS_PREFIX
from apbs_analysis.export_dx import write_dx
from apbs_analysis.interaction_map import interaction_grid


TEMPLATE = '''# {complex_id} -- complex vs isolated chains
# Potentials in kT/e. All maps share one lattice, so they overlay exactly.
# Generated by apbs_analysis.pymol_compare

load {complex_pqr}, {complex_id}_complex
load {complex_dx}, map_complex
{chain_loads}
# Clear representations up front. Doing this *after* the show/disable calls
# below would strip the surfaces off the disabled objects, so re-enabling one
# would show nothing at all.
hide everything
bg_color white

# --- complex, coloured by its own potential ---
ramp_new ramp_complex, map_complex, [{lo:.2f}, 0, {hi:.2f}], [red, white, blue]
show surface, {complex_id}_complex
set surface_color, ramp_complex, {complex_id}_complex

# --- each isolated chain, coloured by its own potential ---
{chain_setup}
{interaction_block}
set surface_quality, 1
set two_sided_lighting, on
orient {complex_id}_complex

/print("{complex_id}: objects -> {complex_id}_complex{chain_list}{interaction_name}")
/print("Only the complex is shown. 'enable'/'show surface' the others to compare.")
/print("All maps are on one lattice: {shape} at {spacing} A.")
'''

CHAIN_SETUP = '''ramp_new ramp_{chain}, map_{chain}, [{lo:.2f}, 0, {hi:.2f}], [red, white, blue]
show surface, {complex_id}_{chain}
set surface_color, ramp_{chain}, {complex_id}_{chain}
disable {complex_id}_{chain}
'''

INTERACTION_BLOCK = '''# --- interaction potential: complex minus the isolated chains ---
load {interaction_dx}, map_interaction
load {complex_pqr}, {complex_id}_interaction
ramp_new ramp_interaction, map_interaction, [{ilo:.2f}, 0, {ihi:.2f}], [orange, white, purple]
show surface, {complex_id}_interaction
set surface_color, ramp_interaction, {complex_id}_interaction
disable {complex_id}_interaction
'''


def _relative(path: Path, start: Path) -> str:
    return os.path.relpath(path, start).replace(os.sep, "/")


def build_session(
    complex_id: str,
    complex_dir: Path,
    monomer_dir: Path,
    output_dir: Path,
    chains: list[str],
    ramp: float,
    interaction_ramp: float,
    interaction_dx: Path | None,
    shape: tuple,
    spacing: np.ndarray,
) -> Path:
    complex_pqr = _relative(complex_dir / f"{complex_id}.pqr", output_dir)
    complex_dx = _relative(complex_dir / f"{complex_id}_potential.dx.gz", output_dir)

    chain_loads = "\n".join(
        f"load {_relative(monomer_dir / f'{complex_id}_{chain}.pqr', output_dir)}, {complex_id}_{chain}\n"
        f"load {_relative(monomer_dir / f'{complex_id}_{chain}_potential.dx.gz', output_dir)}, map_{chain}"
        for chain in chains
    )
    chain_setup = "".join(
        CHAIN_SETUP.format(chain=chain, complex_id=complex_id, lo=-ramp, hi=ramp)
        for chain in chains
    )
    interaction_block = ""
    interaction_name = ""
    if interaction_dx is not None:
        interaction_block = INTERACTION_BLOCK.format(
            interaction_dx=_relative(interaction_dx, output_dir),
            complex_pqr=complex_pqr,
            complex_id=complex_id,
            ilo=-interaction_ramp,
            ihi=interaction_ramp,
        )
        interaction_name = f" | {complex_id}_interaction (orange/purple)"

    path = output_dir / f"{complex_id}_compare.pml"
    path.write_text(
        TEMPLATE.format(
            complex_id=complex_id,
            complex_pqr=complex_pqr,
            complex_dx=complex_dx,
            chain_loads=chain_loads,
            chain_setup=chain_setup,
            interaction_block=interaction_block,
            lo=-ramp,
            hi=ramp,
            chain_list="".join(f" | {complex_id}_{chain}" for chain in chains),
            interaction_name=interaction_name,
            shape="x".join(str(int(v)) for v in shape),
            spacing="/".join(f"{v:.3f}" for v in spacing),
        ),
        encoding="utf-8",
    )
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("complex_store")
    parser.add_argument("monomer_store")
    parser.add_argument("complexes", nargs="*", help="Complex ids (default: all)")
    parser.add_argument("--complex-dir", required=True, help="Directory pymol_export wrote the complexes into")
    parser.add_argument("--monomer-dir", required=True, help="Directory pymol_export wrote the monomers into")
    parser.add_argument("-o", "--output-dir", required=True, help="Where the _compare.pml files go")
    parser.add_argument("--interaction-dir", help="Also build interaction maps here (default: <output-dir>/interaction)")
    parser.add_argument("--no-interaction", action="store_true", help="Skip the difference map")
    parser.add_argument("--ramp", type=float, default=5.0)
    parser.add_argument("--interaction-ramp", type=float, default=2.0)
    args = parser.parse_args()

    complex_store = Path(args.complex_store).expanduser()
    monomer_store = Path(args.monomer_store).expanduser()
    complex_dir = Path(args.complex_dir).expanduser().resolve()
    monomer_dir = Path(args.monomer_dir).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    interaction_dir = Path(
        args.interaction_dir or output_dir / "interaction"
    ).expanduser().resolve()

    with h5py.File(complex_store, "r") as complexes, h5py.File(monomer_store, "r") as monomers:
        available = sorted(n for n in complexes if not n.startswith(IN_PROGRESS_PREFIX))
        chains_of: dict[str, list[str]] = {}
        for name in monomers:
            if name.startswith(IN_PROGRESS_PREFIX):
                continue
            parent = str(monomers[name].attrs.get("parent_complex_id", ""))
            chains_of.setdefault(parent, []).append(str(monomers[name].attrs["chain"]))
        geometry = {
            name: (tuple(complexes[name].attrs["grid_shape"]),
                   np.asarray(complexes[name].attrs["grid_spacing"], dtype=float))
            for name in available
        }

    targets = args.complexes or available
    missing = [name for name in targets if name not in available]
    if missing:
        sys.exit(f"Not in the complex store: {', '.join(missing)}")

    written = 0
    skipped: list[str] = []
    for index, complex_id in enumerate(targets, start=1):
        chains = sorted(chains_of.get(complex_id, []))
        if not chains:
            skipped.append(complex_id)
            continue
        # Only reference files that actually exist, so a session never fails to load.
        required = [complex_dir / f"{complex_id}.pqr", complex_dir / f"{complex_id}_potential.dx.gz"]
        required += [monomer_dir / f"{complex_id}_{c}_potential.dx.gz" for c in chains]
        if any(not path.is_file() for path in required):
            skipped.append(complex_id)
            continue

        interaction_dx = None
        if not args.no_interaction:
            interaction_dir.mkdir(parents=True, exist_ok=True)
            interaction_dx = interaction_dir / f"{complex_id}_interaction.dx.gz"
            if not interaction_dx.is_file():
                grid, _chains = interaction_grid(complex_store, monomer_store, complex_id)
                write_dx(grid, interaction_dx)

        shape, spacing = geometry[complex_id]
        build_session(
            complex_id, complex_dir, monomer_dir, output_dir, chains,
            args.ramp, args.interaction_ramp, interaction_dx, shape, spacing,
        )
        written += 1
        if len(targets) > 1 and index % 10 == 0:
            print(f"  built {index}/{len(targets)} sessions", flush=True)

    print(f"Wrote {written} comparison session(s) into {output_dir}")
    if skipped:
        print(f"Skipped {len(skipped)} without exported monomer files: {', '.join(skipped[:5])}")
    if written:
        first = targets[0] if targets[0] not in skipped else None
        if first:
            print(f"Open with:  pymol {output_dir / (first + '_compare.pml')}")


if __name__ == "__main__":
    main()
